name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  go-test:
    name: Go ${{ matrix.go }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go: ['1.25.x']
        os: [ubuntu-latest, ubuntu-24.04-arm64, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
          cache: true

      - name: Run unit tests
        run: make test

      - name: Run race detector
        if: startsWith(matrix.os, 'ubuntu')
        run: go test -race ./...
